export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST';
export const CREATE_CLASS_SUCCESSED = 'CREATE_CLASS_SUCCESSED';
export const CREATE_CLASS_FAILED = 'CREATE_CLASS_FAILED';

export const GET_CLASSES_REQUEST = 'GET_CLASSES_REQUEST';
export const GET_CLASSES_SUCCESSED = 'GET_CLASSES_SUCCESSED';
export const GET_CLASSES_FAILED = 'GET_CLASSES_FAILED';

export const SELECT_CLASS = 'SELECT_CLASS';

export const SELECT_COLLECTION = 'SELECT_COLLECTION';

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST';
export const UPDATE_CLASS_SUCCESSED = 'UPDATE_CLASS_SUCCESSED';
export const UPDATE_CLASS_FAILED = 'UPDATE_CLASS_FAILED';

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST';
export const DELETE_CLASS_SUCCESSED = 'DELETE_CLASS_SUCCESSED';
export const DELETE_CLASS_FAILED = 'DELETE_CLASS_FAILED';

export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_SUCCESSED = 'CREATE_COLLECTION_SUCCESSED';
export const CREATE_COLLECTION_FAILED = 'CREATE_COLLECTION_FAILED';

export const GET_COLLECTIONS_REQUEST = 'GET_COLLECTIONS_REQUEST';
export const GET_COLLECTIONS_SUCCESSED = 'GET_COLLECTIONS_SUCCESSED';
export const GET_COLLECTIONS_FAILED = 'GET_COLLECTIONS_FAILED';

export const UPDATE_COLLECTION_REQUEST = 'UPDATE_COLLECTION_REQUEST';
export const UPDATE_COLLECTION_SUCCESSED = 'UPDATE_COLLECTION_SUCCESSED';
export const UPDATE_COLLECTION_FAILED = 'UPDATE_COLLECTION_FAILED';
