export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSED = 'USER_LOGIN_SUCCESSED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESSED = 'USER_LOGOUT_SUCCESSED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';
